orders/urls.py
from django.urls import path
from . import views

app_name = 'orders'

urlpatterns = [
    path('', views.book_order, name='order_book'),
    path('create/', views.order_create, name='order_create'),
    path('admin/order/<int:order_id>/', views.admin_order_detail, name='admin_order_detail'),
    path('admin/order/<int:order_id>/pdf/', views.admin_order_pdf, name='admin_order_pdf'),
    path('checkout_page', views.checkout_page, name="checkout_page"),
]

shop/urls.py
from django.urls import path
from . import views
from django.conf import settings
from django.conf.urls.static import static
# Authentications
from .views import RegisterViewnew , product_list ,LoginView  , logoutUser

app_name = 'shop'

urlpatterns = [


     path('register/', RegisterViewnew.as_view(), name="register_user" ),
     path('login/', LoginView.as_view() , name="login_page"),
     path('logout/', logoutUser, name="logout"),
     path('FAQ', views.FAQ, name="FAQ"),
     path('About', views.About, name="About"),
     path('profile/', views.profile, name='profile'),

     path('', product_list, name='product_list'),
     path('<slug:category_slug>/', views.product_list, name='product_list_by_category'),
     path('<int:id>/<slug:slug>/', views.product_detail,name='product_detail'),

]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

orders/models.py
from django.db import models
# from shop.models import Product
from django.utils import timezone
from django.contrib.auth.models import User


class Order(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE, null=True)
    first_name = models.CharField(max_length=50)
    last_name = models.CharField(max_length=50)
    email = models.EmailField()
    address = models.CharField(max_length=250)
    postal_code = models.CharField(max_length=20)
    city = models.CharField(max_length=100)
    created = models.DateTimeField(auto_now_add=True)
    updated = models.DateTimeField(auto_now=True)
    paid = models.BooleanField(default=False)
    braintree_id = models.CharField(max_length=150, blank=True)
    travel_date = models.DateField(default=timezone.now)
    travel_time = models.CharField(default='', max_length=15)

    class Meta:
        ordering = ('-created',)

    def __str__(self):
        return 'Order {}'.format(self.id)

    def get_total_cost(self):
        return sum(item.get_cost() for item in self.items.all())


class OrderItem(models.Model):
    order = models.ForeignKey(Order,
                              related_name='items',
                              on_delete=models.CASCADE)
    product = models.ForeignKey('shop.Product',  # import Product model here
                                related_name='order_items',
                                on_delete=models.CASCADE)
    price = models.DecimalField(max_digits=10, decimal_places=2)
    quantity = models.PositiveIntegerField(default=1)

    def __str__(self):
        return '{}'.format(self.id)

    def get_cost(self):
        return self.price * self.quantity

orders/forms.py
from django import forms
from .models import Order


class OrderCreateForm(forms.ModelForm):
    class Meta:
        model = Order
        fields = ['first_name', 'last_name', 'email', 'address',
                  'postal_code', 'city',
                  'travel_date', 'travel_time']

orders/views.py
from django.urls import reverse
from django.shortcuts import render, redirect
from .models import OrderItem
from .forms import OrderCreateForm
from cart.cart import Cart
from django.contrib.admin.views.decorators import staff_member_required
from django.shortcuts import get_object_or_404
from .models import Order
from django.conf import settings
from django.http import HttpResponse
from django.template.loader import render_to_string
from django.contrib.auth.decorators import login_required
from django.contrib.auth.models import User


# import weasyprint

@staff_member_required
def admin_order_pdf(request, order_id):
    order = get_object_or_404(Order, id=order_id)
    html = render_to_string('orders/order/pdf.html',
                            {'order': order})
    response = HttpResponse(content_type='application/pdf')
    response['Content-Disposition'] = 'filename=\
        "order_{}.pdf"'.format(order.id)
    weasyprint.HTML(string=html).write_pdf(response,
                                           stylesheets=[weasyprint.CSS(
                                               settings.STATIC_ROOT + 'css/pdf.css')])
    return response


@staff_member_required
def admin_order_detail(request, order_id):
    order = get_object_or_404(Order, id=order_id)
    return render(request,
                  'admin/orders/order/detail.html',
                  {'order': order})


@login_required
def order_create(request):
    cart = Cart(request)
    if request.method == 'POST':
        form = OrderCreateForm(request.POST)
        if form.is_valid():
            order = form.save(commit=False)
            order.user = request.user  # set the user field
            order.save()
            for item in cart:
                OrderItem.objects.create(order=order,
                                         product=item['product'],
                                         price=item['price'],
                                         quantity=item['quantity'])
            # clear the cart
            cart.clear()
            # set the order in the session
            request.session['order_id'] = order.id
            # redirect for payment
            return redirect(reverse('payment:process'))

    else:
        form = OrderCreateForm()
    return render(request,
                  'orders/order/create.html',
                  {'cart': cart, 'form': form})


def checkout_page(request):
    return None


def book_order(request):
    return render(request,
                  'orders/order/book.html')

orders/templates/orders/order/book.html
{% extends "shop/base.html" %}
{% load static %}

{% block title %}
  Your shopping cart
{% endblock %}

{% block content %}
<div class="container">
    <link href="{% static "css/style.css" %}" rel="stylesheet">
    <div>
        <div id="root"></div>
        <div id="input-date">Seleted Date: </div>
    </div>
    <div id="timepicker">
    </div>
    <script src="{% static "js/timepicker.js" %}"></script>
    <script src="{% static "js/book.js" %}"></script>
    <script>
        function checkout(url) {
            if(selectDate != "" && picker.getTimeString() != "") {
                location.href = url + "?date="+selectDate+"&time="+picker.getTimeString();
            }
        }
    </script>
</div>
<p class="text-right" style="margin-top: 50px;">
    <a href="{% url "shop:product_list" %}" class="button light">Continue shopping</a>
    <a onclick="checkout('{% url "orders:order_create" %}')" class="button">
      Checkout
    </a>
  </p>
{% endblock %}

orders/templates/orders/order/create.html
{% extends "shop/base.html" %}

{% block title %}
    Checkout
{% endblock %}

{% block content %}
    <h1>Checkout</h1>

    <div class="order-info">
        <h3>Your order</h3>
        <ul>
            {% for item in cart %}
                <li>
                    {{ item.quantity }}x {{ item.product.name }}
                    <span>${{ item.total_price }}</span>
                </li>
            {% endfor %}
        </ul>
        <p>Total: ${{ cart.get_total_price }}</p>
    </div>

    <form action="." method="post" class="order-form">
        {{ form.as_p }}
        <p>
            <input type="submit" value="Place order">
            <a href="../../../../cart/templates/checkout_page.html" class="link">
            </a>
        </p>

        <script>
            const searchParams = new URLSearchParams(window.location.search);

            const selectedDate = searchParams.get('date');
            const selectedTime = searchParams.get('time');

            document.getElementById('id_travel_date').value = selectedDate;
            document.getElementById('id_travel_time').value = selectedTime;
        </script>

        {% csrf_token %}
    </form>
{% endblock %}

orders/templates/orders/order/pdf.html
<html> 
<body> 
  <h1>My Shop</h1> 
  <p> 
    Invoice no. {{ order.id }}</br> 
    <span class="secondary"> 
      {{ order.created|date:"M d, Y" }} 
    </span> 
  </p> 
 
  <h3>Bill to</h3> 
  <p> 
    {{ order.first_name }} {{ order.last_name }}<br> 
    {{ order.email }}<br> 
    {{ order.address }}<br> 
    {{ order.postal_code }}, {{ order.city }}
  </p> 
 
  <h3>Items bought</h3> 
  <table> 
    <thead> 
      <tr> 
        <th>Product</th> 
        <th>Price</th> 
        <th>Quantity</th> 
        <th>Cost</th> 
      </tr> 
    </thead> 
    <tbody> 
      {% for item in order.items.all %} 
        <tr class="row{% cycle "1" "2" %}"> 
          <td>{{ item.product.name }}</td> 
          <td class="num">${{ item.price }}</td> 
          <td class="num">{{ item.quantity }}</td> 
          <td class="num">${{ item.get_cost }}</td> 
        </tr> 
      {% endfor %} 
      <tr class="total"> 
        <td colspan="3">Total</td> 
        <td class="num">${{ order.get_total_cost }}</td> 
      </tr> 
    </tbody> 
  </table> 
     
  <span class="{% if order.paid %}paid{% else %}pending{% endif %}"> 
    {% if order.paid %}Paid{% else %}Pending payment{% endif %} 
  </span> 
</body> 
</html> 