shop/urls.py
from django.urls import path
from . import views
from django.conf import settings
from django.conf.urls.static import static
# Authentications
from .views import RegisterViewnew , product_list ,LoginView  , logoutUser

app_name = 'shop'

urlpatterns = [


     path('register/', RegisterViewnew.as_view(), name="register_user" ),
     path('login/', LoginView.as_view() , name="login_page"),
     path('logout/', logoutUser, name="logout"),
     path('FAQ', views.FAQ, name="FAQ"),
     path('About', views.About, name="About"),
     path('profile/', views.profile, name='profile'),

     path('', product_list, name='product_list'),
     path('<slug:category_slug>/', views.product_list, name='product_list_by_category'),
     path('<int:id>/<slug:slug>/', views.product_detail,name='product_detail'),

]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

shop/models.py
from django.db import models
from django.urls import reverse
from django.contrib.auth.models import User
from PIL import Image
from orders.models import Order


class Category(models.Model):
    name = models.CharField(max_length=200,
                            db_index=True)
    slug = models.SlugField(max_length=200,
                            unique=True)

    class Meta:
        ordering = ('name',)
        verbose_name = 'category'
        verbose_name_plural = 'categories'

    def __str__(self):
        return self.name

    def get_absolute_url(self):
        return reverse('shop:product_list_by_category',
                       args=[self.slug])


class Product(models.Model):
    category = models.ForeignKey(Category,
                                 related_name='products',
                                 on_delete=models.CASCADE)
    name = models.CharField(max_length=200, db_index=True)
    slug = models.SlugField(max_length=200, db_index=True)
    image = models.ImageField(upload_to='products/%Y/%m/%d',
                              blank=True)
    description = models.TextField(blank=True)
    price = models.DecimalField(max_digits=10, decimal_places=2)
    available = models.BooleanField(default=True)
    created = models.DateTimeField(auto_now_add=True)
    updated = models.DateTimeField(auto_now=True)

    class Meta:
        ordering = ('name',)
        index_together = (('id', 'slug'),)

    def __str__(self):
        return self.name

    def get_absolute_url(self):
        return reverse('shop:product_detail',
                       args=[self.id, self.slug])


class Profile(models.Model):
    user = models.OneToOneField(User, on_delete=models.CASCADE)  # Delete profile when user is deleted
    image = models.ImageField(default='default.jpg', upload_to='profile_pics')
    biography = models.TextField(default='Tell us about yourself')
    preferences = models.TextField(default='Describe your travel preferences')

    def get_orders(self):
        return Order.objects.filter(user=self.user)

    def get_orders_with_details(self):
        orders = Order.objects.filter(user=self.user)
        order_details = []
        for order in orders:
            order_items = OrderItem.objects.filter(order=order)
            order_details.append({'order': order, 'items': order_items})
        for order_detail in order_details:
            for item in order_detail['items']:
                item.product_name = Product.objects.get(id=item.product_id).name
        return order_details

    def __str__(self):
        return f'{self.user.username} Profile'  # show how we want it to be displayed

    def save(self, **kwargs):
        super().save()

        img = Image.open(self.image.path)

        if img.height > 300 or img.width > 300:
            output_size = (300, 300)
            img.thumbnail(output_size)
            img.save(self.image.path)

shop/templates/shop/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head style="background-color: lavender">
  <meta charset="utf-8" />
  <title>{% block title %}Intergalactic Travel Agency{% endblock %}</title>

  <!-- Links for BootStrap which is also supporting Validation  -->
  <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/css/bootstrap.min.css" integrity="sha384-MCw98/SFnGE8fJT3GXwEOngsV7Zt27NXFoaoApmYm81iuXoPkFOJwJ8ERdknLPMO" crossorigin="anonymous">

  <script src="https://code.jquery.com/jquery-3.2.1.slim.min.js" integrity="sha384-KJ3o2DKtIkvYIK3UENzmM7KCkRr/rE9/Qpg6aAZGJwFDMVNA/GpGFF93hXpG5KkN" crossorigin="anonymous"></script>
  <script src="https://cdn.jsdelivr.net/npm/popper.js@1.12.9/dist/umd/popper.min.js" integrity="sha384-ApNbgh9B+Y1QKtv3Rn7W3mgPxhU9K/ScQsAP7hUibX39j7fakFPskvXusvfa0b4Q" crossorigin="anonymous"></script>
  <script src="https://cdn.jsdelivr.net/npm/bootstrap@4.0.0/dist/js/bootstrap.min.js" integrity="sha384-JZR6Spejh4U02d8jOt6vLEHfe/JQGiRRSQQxSfFWpi1MquVdAyjUar5+76PVCmYl" crossorigin="anonymous"></script>  <!-- End Links  -->

 <link href="{% static "css/base.css" %}" rel="stylesheet">
</head>
<body style="background-color: lavender">
<div id="header" style="display: flex; align-items: left;">
  <a href="/" style="margin-right: 10px;"> <img src="\media\products\logo.png" style="height: 50px;"></a>
  <h1 style="color: #0c158a; font-weight: bold; font-size: 36px; margin: 0;"><a href="/" style="color: #0c158a; text-decoration: none;">Intergalactic Travel Agency</a></h1>
</div>
  <div id="subheader" style="background-color: lavender">
    {% if request.user.is_authenticated %}
    <div class="cart">
      {% with total_items=cart|length %}
          {% if cart|length > 0 %}
            Your cart:
            <a href="{% url "cart:cart_detail" %}">
              {{ total_items }} item{{ total_items|pluralize }},
              ${{ cart.get_total_price }}
            </a>
          {% else %}
            Your cart is empty.
          {% endif %}
        {% endwith %}
    </div>
    {% endif %}
    <!-- For cart auth just move the cart div to user.isauthenticated -->
    <div class="cart" style="background-color: lavender">

      {% if request.user.is_authenticated %}
       <a href="{% url 'shop:profile' %}">
       | Profile |
      </a>
          <a href="{% url 'shop:logout' %}">
       | LogOut |
      </a>

      {% else  %}
      <a href="{% url 'shop:login_page' %}">
       | Login |
      </a>
      <a href="{% url 'shop:register_user' %}">
       | Register |
      </a>
      {% endif %}


            {% if request.user.is_authenticated %}
         <span>| {{ request.user }} |</span>
         {% endif %}

    </div>
  </div>
  <div id="content" style="background-color: lavender">
    {% block content %}
    {% endblock %}
  </div>
</body>
<br>
<footer>
</footer>
<br>
  <div class="link-container" style="background-color: lavender">
      <div>
          <h2> <a href = "FAQ" class="link">FAQ</a></h2>
      </div>
      <div class="contact-container">
         <h2>Contact</h2>
         <p>On Planet Earth: 000-431-0000</p>
          <p> Interdimmensional Hotline: 000-999-000-999 </p>
         <p>Email: WorldlyTravel@EverythingandEverywhere.com</p>
      </div>
      <div>
         <h2><a href= "About" class="link">About</a></h2>
      </div>
   </div>
<style>
   .link {
      color: rgb(00, 00, 00);
      text-decoration: none;
   }
   .link:hover {
      text-decoration: underline;
   }
   .link-container {
      display: flex;
      flex-direction: row;
      flex-wrap: wrap;
      justify-content: space-around;
   }
   .contact-container {
      text-align: center;
   }
   .contact-container h2 {
      font-weight: 600;
      margin-bottom: 0;
   }
   .contact-container p {
      font-weight: 600;
      font-size: 15px;
      margin-bottom: 0;
   }
</style>
</html>